# Generated by Django 3.0.1 on 2021-01-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('registered_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('section', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('domain_mail', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='studregister',
            fields=[
                ('uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'studregister',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='')),
                ('registered_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.details')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='adetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('intermediate_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('btech_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('backlogs', models.IntegerField()),
                ('one_one_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('one_two_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('two_one_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('two_two_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('three_one_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('three_two_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('four_one_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('four_two_SGPA', models.DecimalField(decimal_places=5, max_digits=10)),
                ('certifications', models.TextField(max_length=400)),
                ('workshops', models.TextField(max_length=400)),
                ('mini_projects', models.TextField(max_length=400)),
                ('projects', models.TextField(max_length=400)),
                ('job_internships', models.TextField(max_length=400)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.details')),
            ],
            options={
                'db_table': 'adetails',
            },
        ),
    ]
